package reengine

import (
	"crypto/aes"
	"crypto/cipher"
	"encoding/binary"
	"errors"
	"fmt"
	"math/big"
)

// Mandarin is the "flags=0x10" cipher Resident Evil Requiem (RE9) uses on
// both platforms (unlike RE4's Lime, which is Steam-only - RE4's PS5
// build is plain Blowfish - Requiem uses Mandarin on both sides, and
// carries no HasID field at all: account identity lives entirely in
// which key is used to decrypt, not in any plaintext/encrypted field
// inside the container). A block-oriented scheme layering AES-128-OFB
// over CityHash64-checksummed chunks, with per-block key/iv material
// generated by a SplitMix64 PRNG seeded by two title-specific constants
// plus an account-bound key. Each block also carries an ElGamal-style
// authenticated copy of its own key/iv, using the exact same P/Q/R group
// RE4's Lime cipher uses (see lime.go) - Capcom's own internal naming
// for the two schemes is "Mandarin"/"Lime" per community reverse
// engineering, hence the fruit names throughout this codebase.
//
// Format facts (seeds, block layout, PRNG/cipher/checksum sequencing)
// cross-referenced against kvasszn/ree-save-editor's public Rust source
// for facts only (the same standard used for RE4's Lime and RE2's
// Blowfish-LE elsewhere in this package) - this Go implementation is
// original, not ported, except cityhash.go's checksum (ported verbatim,
// since a checksum must match bit-for-bit or the format rejects the
// save outright - see that file's own doc comment).
//
// One piece is deliberately NOT faithfully reproduced: the 0x80-byte
// trailer after the last block, which the reference tool's own decoder
// never reads back (only logs) - its own author flagged the RSA modulus
// used to build it as an unverified guess ("idk if the other one is
// right"). This package writes zeros there. If a real save turns out to
// need it, that's a live-testing finding, not a guess to make upfront.
const (
	mandarinBlockUnit  = 0x4000 // one "unit" of a block's plaintext size; each block is 1-8 units
	mandarinMetaSize   = 0x210  // per-block ElGamal key/iv pairs (4x128) + checksum (8) + 8 reserved bytes
	mandarinTailSize   = 0x80   // unused trailing bytes after the last block - written as zeros, see above
	MandarinDataOffset = 0x10   // header (12 bytes) aligned up to 16; no HasID/Blowfish fields for RE9
)

// mandarinSeedsRE9 is Requiem's SplitMix64 seed pair, confirmed against
// real PC and PS5 saves (see convert.go's Requiem TitleConfig and
// docs/dev-res9.md). rsaRand seeds the unused trailer above and is kept
// only for documentation completeness.
var mandarinSeedsRE9 = struct{ rsaRand, encRand uint64 }{
	rsaRand: 0,
	encRand: 0x61f6868699c14dfa,
}

// SplitMix64 is the PRNG Mandarin uses to derive block sizes, per-block
// AES key/iv material, and the metadata XOR mask - a standard, public
// PRNG (not a secret algorithm), confirmed against real saves via the
// block checksum oracle (see MandarinDecode).
const (
	splitMix64Add  = 0x9e3779b97f4a7c15
	splitMix64Mul1 = 0xbf58476d1ce4e5b9
	splitMix64Mul2 = 0x94d049bb133111eb
)

func splitMix64Next(state *uint64) uint64 {
	*state += splitMix64Add
	z := *state
	z = (z ^ (z >> 30)) * splitMix64Mul1
	z = (z ^ (z >> 27)) * splitMix64Mul2
	return z ^ (z >> 31)
}

// mandarinExponent derives the per-account ElGamal exponent: bitwise-NOT
// of the full 64-bit key, reduced mod Q. Unlike Lime (RE4), which masks
// its account key to 32 bits first, Mandarin as configured for RE9 uses
// the full 64-bit value unmasked (RE9's key-derivation formula is the
// identity function - see docs/dev-res9.md).
func mandarinExponent(key uint64) *big.Int {
	u := new(big.Int).SetUint64(^key)
	return u.Mod(u, limeQ)
}

// mandarinBlockSizes runs the SplitMix64 sequence that determines every
// potential block's size (in mandarinBlockUnit units, 1-8), returning
// the sizes and the PRNG state immediately after generating all of them
// - callers add the account term to that state before deriving any
// block's key/iv/metadata mask (matching the reference's ordering:
// *all* potential block sizes are drawn before the account key enters
// the stream).
func mandarinBlockSizes(decryptedLen uint64) ([]uint8, uint64) {
	numPotential := decryptedLen >> 14
	if decryptedLen&0x3fff != 0 {
		numPotential++
	}
	sizes := make([]uint8, numPotential)
	state := mandarinSeedsRE9.encRand
	for i := range sizes {
		sizes[i] = uint8(state&7) + 1
		state = splitMix64Next(&state)
	}
	return sizes, state
}

// mandarinRealBlockCount greedily walks sizes to find how many are
// actually needed to cover decryptedLen bytes of plaintext - a save
// shorter than the sum of every potential block's capacity only uses a
// prefix of the sizes sequence, but every size still has to be drawn
// from the PRNG in order for the stream to stay in sync.
func mandarinRealBlockCount(sizes []uint8, decryptedLen uint64) int {
	leftover := decryptedLen
	n := 0
	for _, sz := range sizes {
		b := uint64(sz) * mandarinBlockUnit
		n++
		if leftover <= b {
			break
		}
		leftover -= b
	}
	return n
}

func mandarinBlockKeyIV(state *uint64) (key, iv [16]byte) {
	for j := 0; j < 16; j++ {
		*state = splitMix64Next(state)
		key[j] = byte(*state)
		iv[j] = byte(*state >> 8)
	}
	return
}

func mandarinMaskMeta(state *uint64, buf []byte) {
	for j := range buf {
		*state = splitMix64Next(state)
		buf[j] ^= byte(*state)
	}
}

func mandarinAESOFB(key, iv, data []byte) ([]byte, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	stream := cipher.NewOFB(block, iv)
	out := make([]byte, len(data))
	stream.XORKeyStream(out, data)
	return out, nil
}

// MandarinDecoded is a parsed Mandarin-cipher DSSS save.
type MandarinDecoded struct {
	Body      []byte
	HashValid bool
}

// MandarinHeaderValid does a structural-only check of a Mandarin-cipher
// DSSS file's header, without needing the account key MandarinDecode
// requires to actually decrypt it.
func MandarinHeaderValid(data []byte) error {
	if len(data) < MandarinDataOffset+mandarinTailSize+8+4 {
		return errors.New("file too short to be a Mandarin DSSS save")
	}
	if string(data[0:4]) != "DSSS" {
		return errors.New("missing DSSS magic")
	}
	version := binary.LittleEndian.Uint32(data[4:8])
	if version != 2 {
		return fmt.Errorf("unsupported DSSS version %d (only 2 is known)", version)
	}
	flags := binary.LittleEndian.Uint32(data[8:12])
	if flags != flagMandarin {
		return fmt.Errorf("flags %#x aren't the Mandarin shape (want %#x)", flags, flagMandarin)
	}
	return nil
}

// MandarinDecode parses and decrypts a Mandarin-cipher DSSS save (RE9's
// shape on both PC and PS5). key is the account-bound value RE9 derives
// its per-block cipher material from - a wrong one produces a checksum
// mismatch on the very first block, reported as an error rather than
// silently returning garbage.
func MandarinDecode(data []byte, key uint64) (MandarinDecoded, error) {
	if err := MandarinHeaderValid(data); err != nil {
		return MandarinDecoded{}, err
	}

	decryptedLen := binary.LittleEndian.Uint64(data[len(data)-12 : len(data)-4])
	enc := data[MandarinDataOffset : len(data)-4]

	sizes, stateAfterSizes := mandarinBlockSizes(decryptedLen)
	numReal := mandarinRealBlockCount(sizes, decryptedLen)
	state := stateAfterSizes + ^key

	body := make([]byte, 0, decryptedLen)
	remaining := decryptedLen
	pos := 0
	for i := 0; i < numReal; i++ {
		blockSize := int(sizes[i]) * mandarinBlockUnit
		readSize := blockSize + mandarinMetaSize
		if pos+readSize > len(enc) {
			return MandarinDecoded{}, fmt.Errorf("block %d: needs %d bytes, only %d remain", i, readSize, len(enc)-pos)
		}
		buf := append([]byte(nil), enc[pos:pos+readSize]...)

		key16, iv16 := mandarinBlockKeyIV(&state)
		mandarinMaskMeta(&state, buf[:mandarinMetaSize])
		targetChecksum := binary.LittleEndian.Uint64(buf[512:520])

		plain, err := mandarinAESOFB(key16[:], iv16[:], buf[mandarinMetaSize:mandarinMetaSize+blockSize])
		if err != nil {
			return MandarinDecoded{}, fmt.Errorf("block %d: %w", i, err)
		}

		toCopy := blockSize
		if uint64(toCopy) > remaining {
			toCopy = int(remaining)
		}
		checksum := cityHash64(plain[:toCopy])
		if checksum != targetChecksum {
			return MandarinDecoded{}, fmt.Errorf("block %d: checksum mismatch (target=%#x got=%#x) - wrong account key, or the save is corrupt", i, targetChecksum, checksum)
		}
		body = append(body, plain[:toCopy]...)
		remaining -= uint64(toCopy)
		pos += readSize
	}

	storedHash := binary.LittleEndian.Uint32(data[len(data)-4:])
	computedHash := murmur3_32(data[:len(data)-4], 0xffffffff)

	return MandarinDecoded{Body: body, HashValid: storedHash == computedHash}, nil
}

// MandarinEncode builds a Mandarin-cipher DSSS file (RE9's shape) around
// body (RSZ field data serialized at MandarinDataOffset). key selects
// which account's cipher material the file will decrypt with - it must
// be the account that will load it, or MandarinDecode will reject the
// first block.
func MandarinEncode(body []byte, key uint64) ([]byte, error) {
	decryptedLen := uint64(len(body))
	sizes, stateAfterSizes := mandarinBlockSizes(decryptedLen)
	numReal := mandarinRealBlockCount(sizes, decryptedLen)
	state := stateAfterSizes + ^key
	exponent := mandarinExponent(key)

	out := make([]byte, 0, MandarinDataOffset+len(body)*2)
	out = append(out, "DSSS"...)
	out = append(out, u32le(2)...)
	out = append(out, u32le(flagMandarin)...)
	out = append(out, 0, 0, 0, 0) // align up to 16; never read back by the decoder

	pos := 0
	for i := 0; i < numReal; i++ {
		blockSize := int(sizes[i]) * mandarinBlockUnit
		toCopy := blockSize
		if pos+toCopy > len(body) {
			toCopy = len(body) - pos
		}

		key16, iv16 := mandarinBlockKeyIV(&state)

		plain := make([]byte, blockSize)
		copy(plain, body[pos:pos+toCopy])
		checksum := cityHash64(plain[:toCopy])

		enc, err := mandarinAESOFB(key16[:], iv16[:], plain)
		if err != nil {
			return nil, fmt.Errorf("block %d: %w", i, err)
		}

		meta := make([]byte, mandarinMetaSize)
		// The ElGamal auth pairs authenticate 32 bytes (key||iv) as four
		// 8-byte chunks.
		var keyIV [32]byte
		copy(keyIV[0:16], key16[:])
		copy(keyIV[16:32], iv16[:])
		for p := 0; p < 4; p++ {
			c0, c1 := limeEncryptPair(keyIV[p*8:p*8+8], exponent)
			copy(meta[p*128:p*128+64], c0)
			copy(meta[p*128+64:p*128+128], c1)
		}
		binary.LittleEndian.PutUint64(meta[512:520], checksum)
		// meta[520:528] left zero - "litterally_no_idea" per the reference

		mandarinMaskMeta(&state, meta)

		out = append(out, meta...)
		out = append(out, enc...)
		pos += toCopy
	}

	out = append(out, make([]byte, mandarinTailSize)...)

	var lenBytes [8]byte
	binary.LittleEndian.PutUint64(lenBytes[:], decryptedLen)
	out = append(out, lenBytes[:]...)

	hash := murmur3_32(out, 0xffffffff)
	out = append(out, u32le(hash)...)

	return out, nil
}

func u32le(v uint32) []byte {
	var b [4]byte
	binary.LittleEndian.PutUint32(b[:], v)
	return b[:]
}

// MandarinKeyOracle exposes the known-plaintext oracle that makes
// account-key discovery cheap, the same technique that found RE4's
// Blowfish key (see docs/dev-res4.md). Every block's metadata begins
// with the ElGamal pair's first component, which is the *constant*
// x0 = r^e mod p - independent of both key and plaintext. XORing the
// real file's first 8 metadata bytes against it therefore recovers 8
// bytes of the PRNG mask without knowing the key, and MandarinMaskFor
// then tests any candidate key in ~25 PRNG steps rather than a full
// trial decryption.
//
// Returns the recovered mask (as a little-endian uint64) and the PRNG
// state the block-size pass ends on, which MandarinMaskFor needs.
func MandarinKeyOracle(data []byte) (mask uint64, stateAfterSizes uint64) {
	decryptedLen := binary.LittleEndian.Uint64(data[len(data)-12 : len(data)-4])
	_, state := mandarinBlockSizes(decryptedLen)
	x0 := bigIntToLEBytes(limeX0, 64)
	var m [8]byte
	for i := 0; i < 8; i++ {
		m[i] = data[MandarinDataOffset+i] ^ x0[i]
	}
	return binary.LittleEndian.Uint64(m[:]), state
}

// MandarinMaskFor computes the mask a candidate key would produce, for
// comparison against MandarinKeyOracle's recovered value. A match means
// the candidate is the file's key.
func MandarinMaskFor(stateAfterSizes, key uint64) uint64 {
	state := stateAfterSizes + ^key
	for i := 0; i < 16; i++ { // the per-block AES key/iv draw
		state = splitMix64Next(&state)
	}
	var m [8]byte
	for i := 0; i < 8; i++ {
		state = splitMix64Next(&state)
		m[i] = byte(state)
	}
	return binary.LittleEndian.Uint64(m[:])
}
